import assert from "node:assert/strict";
import fs from "node:fs";

const app = fs.readFileSync(new URL("../src/app.js", import.meta.url), "utf8");
const apiClient = fs.readFileSync(new URL("../src/api-client.js", import.meta.url), "utf8");
const css = fs.readFileSync(new URL("../src/styles.css", import.meta.url), "utf8");

assert.ok(app.includes("function renderTripPlan()"));
assert.ok(app.includes("function renderUnsupportedPlan()"));
assert.ok(app.includes("function recoverUnsupportedPlan()"));
assert.ok(app.includes("Starter trip plan generated for this destination."));
assert.ok(app.includes("registration.update()"));
assert.ok(app.includes("function ensureDestinationIntelligence()"));
assert.ok(app.includes("routeMosaicApi.researchDestination"));
assert.ok(app.includes("async function refreshProviderStatus"));
assert.ok(app.includes("routeMosaicApi.checkProviderHealth"));
assert.ok(app.includes("providerDiagnosticsPanel"));
assert.ok(app.includes("provider.configuration"));
assert.ok(app.includes("Retry Configuration Check"));
assert.ok(app.includes("Trip generation is temporarily unavailable. Please try again later. Your trip inputs are saved in the current session."));
assert.ok(app.includes('wizardFooter("Back", "Save and Exit", "Build My Trip", blocking.length ? "disabled" : "")'));
assert.ok(!app.includes("Destination planning providers are not configured yet"));
assert.ok(!app.includes("Add place and route providers in Vercel"));
assert.ok(!app.includes("Add an OpenAI API key in Vercel"));
assert.ok(!app.includes("/api/destination-profile"));
assert.ok(!app.includes("/api/providers/status"));
assert.ok(!app.includes("/api/trips/"));
assert.ok(apiClient.includes('postAction("/api/planner", "research-destination"'));
assert.ok(apiClient.includes('postAction("/api/planner", "generate-trip"'));
assert.ok(apiClient.includes('postAction("/api/planner", "regenerate-day"'));
assert.ok(apiClient.includes('postAction("/api/locations", "search"'));
assert.ok(apiClient.includes('postAction("/api/provider-health", "status"'));
assert.ok(app.includes("registerGeneratedDestinationProfile"));
assert.ok(app.includes("buildTripPlan"));
assert.ok(app.includes("routeMosaicApi.generateTrip"));
assert.ok(app.includes("routeMosaicApi.generateTrip(state.trip, destinationProfile"));
assert.ok(app.includes("MOCK_DESTINATION_UNAVAILABLE") || app.includes("current demo data"));
assert.ok(app.includes("mockPlanNotice"));
assert.ok(app.includes("Sample planning data."));
assert.ok(app.includes("not live destination research, current availability, live traffic, or verified worldwide coverage"));
assert.ok(app.includes("Regenerate Plan"));
assert.ok(app.includes("Edit Preferences"));
assert.ok(app.includes("Coming Later"));
assert.ok(app.includes("function planOverviewSection()"));
assert.ok(app.includes("function planItinerarySection()"));
assert.ok(app.includes("function planFoodSection()"));
assert.ok(app.includes("function planRouteSection()"));
assert.ok(app.includes("function planBudgetSection()"));
assert.ok(app.includes("function planAdvisoriesSection()"));
assert.ok(app.includes("openReplace:"));
assert.ok(app.includes("openMove:"));
assert.ok(app.includes("openCustomStop"));
assert.ok(app.includes("regenerateDay:"));
assert.ok(app.includes("regenerateMeals"));
assert.ok(app.includes("toggleItemLock:"));
assert.ok(app.includes("toggleDayLock:"));
assert.ok(app.includes("toggleMustDo:"));
assert.ok(app.includes("removeItem:"));
assert.ok(app.includes("state.planStale = true"));
assert.ok(app.includes("No same-region backup is available") || app.includes("Backup options"));
assert.ok(apiClient.includes("INVALID_RESPONSE"));
assert.ok(apiClient.includes("The trip service returned an invalid response."));
assert.ok(!apiClient.includes("Request failed. Please retry."));

assert.ok(css.includes(".plan-hero"));
assert.ok(css.includes(".plan-tabs"));
assert.ok(css.includes(".timeline-item"));
assert.ok(css.includes(".backup-options"));
assert.ok(css.includes(".route-schematic"));
assert.ok(css.includes(".budget-bars"));
assert.ok(css.includes(".advisory-card"));
assert.ok(css.includes("@media (max-width: 700px)"));

console.log("Trip plan UI tests passed");
