import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const app = readFileSync("src/app.js", "utf8");
const css = readFileSync("src/styles.css", "utf8");
const domain = readFileSync("src/domain.js", "utf8");
const tripBasicsChrome = app.match(/function tripBasicsChrome\(trip, travelerCount, issueCount\) \{([\s\S]*?)\nfunction tripSnapshotFacts/)?.[1] || "";

assert.ok(app.includes("Where should your next trip take you?"));
assert.ok(app.includes("Add the essential details. RouteMosaic will use them to shape a realistic itinerary."));
assert.ok(!app.includes("Who is going on this trip?"), "Travelers is no longer a standalone step");
assert.ok(app.includes("Who's Traveling"));
assert.ok(app.includes("Group and special needs."));
assert.ok(app.includes("function whosTravelingSection"));
assert.ok(app.includes("function specialNeedsField"));
assert.ok(app.includes("function budgetAccommodationDetails"));
assert.ok(app.includes("Budget and accommodation"));
assert.ok(app.includes("function dateTimeField"));
assert.ok(app.includes("Arrival Time"));
assert.ok(app.includes("Departure Time"));
assert.ok(app.includes("Interpret My Trip"));
assert.ok(app.includes("Try a sample trip"));
assert.ok(app.includes("Load a realistic Los Angeles example."));
assert.ok(app.includes("Try Los Angeles sample"));
assert.ok(app.includes("Trip Essentials"));
assert.ok(app.includes("Tell us where and when."));
assert.ok(app.includes("Choose your trip shape"));
assert.ok(app.includes("Decide how many bases and how much movement feels right."));
assert.ok(app.includes("Trip Intent"));
assert.ok(app.includes("Tell us what would make this trip feel right."));
assert.ok(app.includes("Apply Selected Preferences"));
assert.ok(app.includes("Save and Exit"));
assert.ok(app.includes("Continue"));
assert.ok(app.includes("Build My Trip"));
assert.ok(app.includes("Cities or Regions to Include"));
assert.ok(app.includes("Select a suggestion to verify this location."));
assert.ok(app.includes("locationField(\"from\""));
assert.ok(app.includes("locationAutocompleteOverlay()"));
assert.ok(app.includes("TravelHeaderIllustration()"));
assert.ok(app.includes("SidebarScenicIllustration()"));
assert.ok(app.includes("visibleReviewIssues"));
assert.ok(app.includes("visibleTripBasicsIssues"));
assert.ok(app.includes("tripBasicsChrome(trip, travelerCount, issueCount)"));
assert.ok(app.includes("tripSnapshotFacts(trip, issueCount)"));
assert.ok(app.includes("Start planning in three simple moves"));
assert.ok(app.includes("Start with where you're going"));
assert.ok(app.includes("Choose your trip shape"));
assert.ok(app.includes("Add what matters most"));
assert.ok(app.includes("if (!interpreted.length) return \"\";"));
assert.ok(app.includes("Route time will be calculated during itinerary planning."));
assert.ok(app.includes("Original Request"));
assert.ok(app.includes("Interpreted Preferences"));
assert.ok(app.includes("What does adventure mean to you?"));
assert.ok(domain.includes("Add Cities or Regions"));
assert.ok(app.includes("Issues"));
assert.ok(app.includes("tripDateSummary"));
assert.ok(app.includes("reconcileTripDates"));
assert.ok(!app.includes("Website-first milestone"));
assert.ok(!app.includes("Quick interpret"));
assert.ok(!app.includes("Interpret description"));
assert.ok(!app.includes("Apply interpretations"));
assert.ok(!app.includes('badge("Ready")'));
assert.ok(!app.includes("Warnings\", issueCount"));
assert.ok(!tripBasicsChrome.includes("metric("));
assert.ok(!app.includes("trip-basics-panel"));
assert.ok(!app.includes("Want to try it first?"));
assert.ok(!app.includes("Try a Sample Los Angeles Trip"));
assert.ok(!app.includes("Generate preview"));
assert.ok(css.includes(".field-shell"));
assert.ok(css.includes(".location-results-panel"));
assert.ok(css.includes(".travel-header-illustration"));
assert.ok(css.includes(".sidebar-scenic-illustration"));
assert.ok(css.includes(".step-1 .top"));
assert.ok(css.includes(".trip-snapshot"));
assert.ok(css.includes(".wizard-main.step-1"));
assert.ok(css.includes(".trip-basics-experience"));
assert.ok(css.includes(".step-1-zone"));
assert.ok(css.includes(".trip-essentials-section"));
assert.ok(css.includes(".trip-structure-section"));
assert.ok(css.includes(".trip-intent-section"));
assert.ok(css.includes(".summary-chips"));
assert.ok(css.includes("@media (prefers-reduced-motion: reduce)"));
assert.ok(!css.includes(".trip-basics-panel"));
assert.ok(css.includes(".derived-summary"));
assert.ok(css.includes(".toast"));

console.log("Trip basics screen tests passed");
